# Generated by Django 3.2.4 on 2021-06-12 19:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Cards',
            new_name='Card',
        ),
        migrations.RenameModel(
            old_name='Players',
            new_name='Player',
        ),
    ]
